### ISSUE TITLE
Block breaks Gutenberg Editor (Version 4.4.0)

### ISSUE THREAD

**Issue by dionysous** [marcusig/gutenberg-section-block#9]
Hello, I am using your custom block and it breaks my editor, when I add it. The error message says:

```
Invariant Violation: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
at cb (http://example.test/wp-content/plugins/gutenberg/vendor/react-dom.min.713f0afa.js:12:450)
at p (http://example.test/wp-content/plugins/gutenberg/vendor/react-dom.min.713f0afa.js:13:214)
at ec (http://example.test/wp-content/plugins/gutenberg/vendor/react-dom.min.713f0afa.js:56:496)
at k (http://example.test/wp-content/plugins/gutenberg/vendor/react-dom.min.713f0afa.js:75:63)
at z (http://example.test/wp-content/plugins/gutenberg/vendor/react-dom.min.713f0afa.js:77:425)
at v (http://example.test/wp-content/plugins/gutenberg/vendor/react-dom.min.713f0afa.js:78:484)
at http://example.test/wp-content/plugins/gutenberg/vendor/react-dom.min.713f0afa.js:82:350
at P (http://example.test/wp-content/plugins/gutenberg/vendor/react-dom.min.713f0afa.js:85:11)
at ph (http://example.test/wp-content/plugins/gutenberg/vendor/react-dom.min.713f0afa.js:100:364)
at eg (http://example.test/wp-content/plugins/gutenberg/vendor/react-dom.min.713f0afa.js:125:307)
```

After that point, editing the page is impossible.

**Comment by lkraav** [comment]
This plugin probably hasn't kept up to date with https://wordpress.org/gutenberg/handbook/reference/deprecated/

**Comment by marcusig** [comment]
@dionysous Thank you for reporting. It should now be fixed.
